language: csharp
dist: trusty
mono: none
dotnet: 2.0.0

script:
 - dotnet restore
 - dotnet build -f netstandard1.6 NSubstituteFSharpWrapper/NSubstituteFSharpWrapper.fsproj
 - dotnet test -f netcoreapp2.0 NSubstituteFSharpWrapper.Tests/NSubstituteFSharpWrapper.Tests.fsproj